// assets.js — 호환성 유지용 re-export 배럴
// 각 파일을 직접 import해도 되고, 기존처럼 assets.js에서 가져와도 동일하게 동작합니다.
//
//   import { FULL_UNIT_LIBRARY } from './unit-data.js';   // 직접
//   import { FULL_UNIT_LIBRARY } from './assets.js';      // 기존 방식 (동일)

export { FULL_UNIT_LIBRARY } from './unit-data.js';

export {
  EQUIPMENT_TYPES,
  EQUIPMENT_TYPE_LABELS,
  EQUIPMENT_TYPE_ICONS,
  EQUIPMENT_RARITIES,
  createEquipmentDrop,
  formatEquipmentStats,
  getEquipmentPower,
} from './equipment-data.js';

export {
  SCREEN_META,
  GROUND_DATA,
  QUEST_DATA,
  DEFAULT_PARTY,
  UNIT_TIER_FOLDERS,
  UNIT_ASSET_FOLDERS,
  UNIT_RENDER_PROFILES,
  MONSTER_RENDER_PROFILE,
} from './game-data.js';

export {
  STORAGE_KEY,
  cloneState,
  FORMATION_ROWS,
  FORMATION_ROW_LABELS,
  FORMATION_ROW_ICONS,
  defaultPartyFormation,
  normalizePartyFormation,
  normalizeVisualProfiles,
  VISUAL_LIMITS,
  fromVisualControlValue,
  getUnitVisualProfile,
  getVisualKey,
  applyVisualProfileToPromotionLine,
  renderVisualVars,
  resetUnitVisualProfile,
  setUnitVisualProfileValue,
  toVisualControlValue,
  getFormationRowForSlot,
  getUnitFormationSlot,
  getUnitFormationRow,
  getUnitBattleRole,
  getUnitJobRoles,
  getUnitJobDisplayLabels,
  getUnitJobDescription,
  renderJobTooltipAttrs,
  getRoleDescription,
  renderRoleTooltipAttrs,
  getFormationRoleFit,
  getFormationStatMultipliers,
  getFormationSummary,
  getRarityColor,
  getRarityStars,
  getRarityStyle,
  getUnitSeriesSynergy,
  getSeriesSynergySummary,
  getRoleComboSummary,
  COMMON_PASSIVES,
  getCommonPassiveDefinition,
  getUnitCommonPassive,
  getPartyCommonPassiveSummary,
  renderStars,
  formatNumber,
  loadAppState,
  saveAppState,
  normalizeEquipmentState,
  getUnitById,
  getPartyUnits,
  getEffectivePartyUnits,
  getPartyPower,
  getReserveUnits,
  getGroundStageState,
  getGroundRewardInfo,
  isGroundUnlocked,
  getFirstUnlockedGroundId,
  getGroundUnlockRequirement,
  getQuestSummary,
  claimQuestReward,
  formatQuestReward,
  normalizeQuestState,
  recordQuestProgress,
  ensureEquipmentState,
  getEquipmentById,
  getEquippedItemsForUnit,
  getUnitEquipmentStats,
  getEffectiveUnitStats,
  resolveGround,
  resolveUnitFolder,
  resolveUnitPortrait,
  resolveUnitImageSprite,
  resolveUnitSprite,
  resolveMonsterSprite,
} from './utils.js';
