export const COMMON_PASSIVE_DATA = [
  {
    id: 'front_guard',
    name: '전열 수호',
    tier: 'common',
    roles: ['탱커', '전사'],
    tags: ['front', 'defense'],
    description: '전열 배치 시 받는 피해가 8% 감소합니다.',
    effects: [{ type: 'damageTakenMul', value: 0.92, condition: 'frontRow' }],
  },
  {
    id: 'iron_stance',
    name: '철벽 태세',
    tier: 'common',
    roles: ['탱커'],
    tags: ['start', 'defense'],
    description: '전투 시작 후 8초 동안 방어가 12% 증가합니다.',
    effects: [{ type: 'defMul', value: 1.12, condition: 'battleStart', duration: 8 }],
  },
  {
    id: 'assault_instinct',
    name: '맹공 본능',
    tier: 'common',
    roles: ['물리 딜러'],
    tags: ['physical', 'damage'],
    description: '물리 피해가 8% 증가합니다.',
    effects: [{ type: 'physicalDamageMul', value: 1.08 }],
  },
  {
    id: 'weakness_spotter',
    name: '약점 포착',
    tier: 'common',
    roles: ['물리 딜러', '도적'],
    tags: ['critical', 'boss'],
    description: '치명타 확률이 6% 증가하고, 보스 대상이면 추가로 4% 증가합니다.',
    effects: [
      { type: 'critChanceAdd', value: 0.06 },
      { type: 'critChanceAdd', value: 0.04, condition: 'targetBoss' },
    ],
  },
  {
    id: 'arcane_training',
    name: '비전 숙련',
    tier: 'common',
    roles: ['마법 딜러'],
    tags: ['magic', 'damage'],
    description: '마법 피해가 8% 증가합니다.',
    effects: [{ type: 'magicDamageMul', value: 1.08 }],
  },
  {
    id: 'elemental_resonance',
    name: '원소 공명',
    tier: 'common',
    roles: ['마법 딜러'],
    tags: ['element', 'weakness'],
    description: '약점 속성으로 공격할 때 피해가 10% 증가합니다.',
    effects: [{ type: 'weaknessDamageMul', value: 1.10 }],
  },
  {
    id: 'healing_touch',
    name: '치유의 손길',
    tier: 'common',
    roles: ['힐러'],
    tags: ['heal'],
    description: '회복량이 12% 증가합니다.',
    effects: [{ type: 'healingMul', value: 1.12 }],
  },
  {
    id: 'emergency_care',
    name: '응급 처치',
    tier: 'common',
    roles: ['힐러'],
    tags: ['heal', 'lowHp'],
    description: '체력 40% 이하인 아군을 회복할 때 회복량이 18% 증가합니다.',
    effects: [{ type: 'healingMul', value: 1.18, condition: 'targetHpBelow40' }],
  },
  {
    id: 'morale_boost',
    name: '사기 고양',
    tier: 'common',
    roles: ['버퍼'],
    tags: ['party', 'start', 'attack'],
    description: '전투 시작 시 파티의 공격과 마력이 5% 증가합니다.',
    effects: [
      { type: 'partyAtkMul', value: 1.05, condition: 'battleStart' },
      { type: 'partyMagMul', value: 1.05, condition: 'battleStart' },
    ],
  },
  {
    id: 'protective_prayer',
    name: '보호 기도',
    tier: 'common',
    roles: ['버퍼', '힐러'],
    tags: ['party', 'start', 'defense'],
    description: '전투 시작 시 파티의 방어와 정신이 5% 증가합니다.',
    effects: [
      { type: 'partyDefMul', value: 1.05, condition: 'battleStart' },
      { type: 'partySprMul', value: 1.05, condition: 'battleStart' },
    ],
  },
  {
    id: 'armor_disruption',
    name: '방어 교란',
    tier: 'common',
    roles: ['디버퍼'],
    tags: ['debuff', 'defense'],
    description: '공격 시 20% 확률로 대상의 방어를 8% 감소시킵니다.',
    effects: [{ type: 'applyDebuff', stat: 'def', value: 0.92, chance: 0.20, duration: 6 }],
  },
  {
    id: 'mind_break',
    name: '정신 붕괴',
    tier: 'common',
    roles: ['디버퍼', '마법 딜러'],
    tags: ['debuff', 'magic'],
    description: '공격 시 20% 확률로 대상의 정신을 8% 감소시킵니다.',
    effects: [{ type: 'applyDebuff', stat: 'spr', value: 0.92, chance: 0.20, duration: 6 }],
  },
  {
    id: 'opening_strike',
    name: '선제 타격',
    tier: 'common',
    roles: ['도적', '물리 딜러'],
    tags: ['waveStart', 'damage'],
    description: '웨이브 시작 후 첫 공격 피해가 18% 증가합니다.',
    effects: [{ type: 'firstHitDamageMul', value: 1.18, condition: 'waveFirstAttack' }],
  },
  {
    id: 'loot_sense',
    name: '전리품 감각',
    tier: 'common',
    roles: ['파밍형'],
    tags: ['reward', 'gold'],
    description: '전투 골드 획득량이 10% 증가합니다.',
    effects: [{ type: 'rewardGoldMul', value: 1.10 }],
  },
  {
    id: 'training_sense',
    name: '수련 감각',
    tier: 'common',
    roles: ['성장형'],
    tags: ['reward', 'growthStone'],
    description: '성장석 획득량이 10% 증가합니다.',
    effects: [{ type: 'rewardGrowthStoneMul', value: 1.10 }],
  },
  {
    id: 'tenacious_vitality',
    name: '끈질긴 생명력',
    tier: 'common',
    roles: ['생존형', '탱커'],
    tags: ['lowHp', 'defense'],
    description: '체력 30% 이하일 때 받는 피해가 12% 감소합니다.',
    effects: [{ type: 'damageTakenMul', value: 0.88, condition: 'selfHpBelow30' }],
  },
  {
    id: 'mana_cycle',
    name: '마력 순환',
    tier: 'common',
    roles: ['마법 딜러', '힐러'],
    tags: ['mp', 'skill'],
    description: '스킬 사용 후 MP를 3 회복합니다.',
    effects: [{ type: 'restoreMp', value: 3, condition: 'afterSkill' }],
  },
  {
    id: 'battle_focus',
    name: '전장의 집중',
    tier: 'common',
    roles: ['범용'],
    tags: ['stack', 'damage'],
    description: '같은 적을 연속 공격할 때 피해가 4% 증가합니다. 최대 12%까지 중첩됩니다.',
    effects: [{ type: 'sameTargetDamageStack', value: 0.04, max: 0.12 }],
  },
  {
    id: 'backline_support',
    name: '후열 지원',
    tier: 'common',
    roles: ['후열 딜러', '서포터'],
    tags: ['back', 'attack'],
    description: '후열 배치 시 공격과 마력이 6% 증가합니다.',
    effects: [
      { type: 'atkMul', value: 1.06, condition: 'backRow' },
      { type: 'magMul', value: 1.06, condition: 'backRow' },
    ],
  },
  {
    id: 'vanguard_breakthrough',
    name: '전열 돌파',
    tier: 'common',
    roles: ['전사', '브루저'],
    tags: ['front', 'attack', 'defense'],
    description: '전열 배치 시 공격이 6%, 방어가 4% 증가합니다.',
    effects: [
      { type: 'atkMul', value: 1.06, condition: 'frontRow' },
      { type: 'defMul', value: 1.04, condition: 'frontRow' },
    ],
  },
];

export const COMMON_PASSIVE_BY_ID = Object.fromEntries(
  COMMON_PASSIVE_DATA.map((passive) => [passive.id, passive]),
);